#!/bin/bash
# Quick Start Guide for ControlNet + Stable Diffusion Project

# Activate virtual environment
source venv/bin/activate

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ControlNet + Stable Diffusion - Smart City Image Generator    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Project Setup Complete! ✓"
echo ""
echo "📁 Project Structure:"
echo "   src/              → Main Python code"
echo "   dataset/          → Place your satellite images here"
echo "   output/           → Generated images will be saved here"
echo "   venv/             → Virtual environment (activated)"
echo ""
echo "🚀 Quick Start Examples:"
echo ""
echo "1. Generate from a satellite image:"
echo "   python3 src/generate_satellite_image.py \\"
echo "     --input dataset/your_satellite_image.png \\"
echo "     --prompt 'modern smart city with solar panels, green spaces' \\"
echo "     --output output/generated_smart_city.png"
echo ""
echo "2. Batch process multiple images:"
echo "   python3 src/batch_generate.py \\"
echo "     --dataset_dir dataset \\"
echo "     --prompt 'futuristic smart city with IoT sensors and 5G towers'"
echo ""
echo "3. Generate from scratch (no input image):"
echo "   python3 src/generate_satellite_image.py \\"
echo "     --prompt 'aerial view of a sustainable smart city' \\"
echo "     --output output/generated_from_scratch.png"
echo ""
echo "📋 Prompt Tips:"
echo "   - Be specific about features (solar panels, green spaces, etc.)"
echo "   - Mention sustainability aspects"
echo "   - Include infrastructure (5G towers, EV charging, etc.)"
echo "   - Add 'high quality, detailed, professional' for better results"
echo ""
echo "⚙️  Performance Options:"
echo "   --steps 20-25     → Fast (lower quality)"
echo "   --steps 30        → Balanced (recommended)"
echo "   --steps 40-50     → Best quality (slower)"
echo "   --guidance_scale  → 7.5 (recommended), higher = stricter prompt"
echo ""
echo "💡 Example Smart City Prompts:"
echo ""
echo "   'aerial satellite view of a modern smart city with:"
echo "   - organized grid layout"
echo "   - solar panel rooftops"
echo "   - autonomous vehicle lanes"
echo "   - 5G tower infrastructure"
echo "   - green roofing and parks"
echo "   - sustainable water management'"
echo ""
echo "📖 For detailed documentation, see README.md"
echo ""
